services:
  server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - /Users/amirhosseinmazaheri/Documents/db_project_sql_server:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "@Amir1990"
    ports:
      - "1433:1433"
